/**
 * Canonical MaxHealth service worker — single source for every PWA (dicom-viewer,
 * consent-app, dtr-app, patient-portal, AIHR, ...). Previously each app shipped its
 * own byte-drifting copy of `public/sw.js` plus a local stamping plugin; this module
 * replaces all of them.
 *
 * Pairs with the page-side {@link "../hooks/use-service-worker-update".useServiceWorkerUpdate}
 * hook + `ServiceWorkerUpdatePrompt` (the "wait + prompt-to-reload" pattern).
 *
 * Usage in an app's `vite.config.ts`:
 * ```ts
 * import { serviceWorkerPlugin } from "@max-health-inc/shared-ui/vite"
 * export default defineConfig({
 *   plugins: [react(), tailwindcss(), serviceWorkerPlugin({ cacheName: "dicom-viewer" })],
 * })
 * ```
 * The app must NOT keep a `public/sw.js` — the plugin emits `dist/sw.js`.
 */
import type { Plugin } from "vite"
import { createHash } from "node:crypto"
import { writeFile } from "node:fs/promises"
import { join } from "node:path"

/** Token replaced at build time with the app's cache-name prefix. */
const APP_NAME_PLACEHOLDER = "__APP_NAME__"
/** Token replaced at build time with a unique, content-derived build id. */
export const BUILD_ID_PLACEHOLDER = "__BUILD_ID__"
/** Token replaced at build time with the JSON precache array. */
const PRECACHE_PLACEHOLDER = "__PRECACHE__"

/**
 * The service-worker source, with placeholders the plugin fills in. It is stored
 * as a string (not a real module) because it runs in the SW global scope and is
 * written verbatim to `dist/sw.js`.
 *
 * Network strategy: cache-first for hashed static assets, network-first for
 * navigations and everything else, `/api/` bypassed. The cache-first branch never
 * stores an HTML response under an asset URL — during a deploy swap a momentarily
 * missing hashed file can 404 to the SPA fallback (index.html, 200); caching that
 * would poison the cache and break MIME ("Refused to apply style ... text/html")
 * on every later load.
 */
export const SERVICE_WORKER_SOURCE = `// GENERATED by @max-health-inc/shared-ui — do not edit by hand.
// MaxHealth PWA service worker. Network-first with offline fallback.
//
// \`${BUILD_ID_PLACEHOLDER}\` is stamped with a unique per-build id so the browser
// detects a fresh SW after each deploy (firing the in-app update prompt) and the
// \`activate\` handler can purge the previous build's caches.
const CACHE_NAME = "${APP_NAME_PLACEHOLDER}-${BUILD_ID_PLACEHOLDER}";

const PRECACHE_ASSETS = ${PRECACHE_PLACEHOLDER};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_ASSETS))
  );
  // Deliberately NOT calling skipWaiting(): an updated SW must WAIT until the user
  // accepts the in-app prompt (which posts SKIP_WAITING). On first install there is
  // no controller, so it activates anyway.
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.pathname.startsWith("/api/")) return;

  if (url.pathname.match(/\\.(png|jpg|jpeg|webp|svg|gif|ico|woff2?|css|js|wasm|dcm)$/)) {
    event.respondWith(cacheFirst(request));
    return;
  }

  event.respondWith(networkFirst(request));
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

// A cached HTML document served for a .css/.js asset request is the SPA fallback
// (index.html, 200) returned for a momentarily-missing hashed file during a deploy.
// Storing it under the asset URL poisons the cache, so never cache it.
function isHtmlFallback(response) {
  return (response.headers.get("content-type") || "").includes("text/html");
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    const response = await fetch(request);
    if (response.ok && !isHtmlFallback(response)) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return new Response("", { status: 408 });
  }
}

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    return cached || new Response("", { status: 408 });
  }
}
`

/**
 * Replace every {@link BUILD_ID_PLACEHOLDER} occurrence with `buildId`, inserted
 * literally (never interpreted as a `String.replace` pattern, so ids with `$` are
 * safe). Returns `source` unchanged when the token is absent.
 */
export function stampServiceWorker(source: string, buildId: string): string {
  if (!source.includes(BUILD_ID_PLACEHOLDER)) return source
  return source.split(BUILD_ID_PLACEHOLDER).join(buildId)
}

export interface ServiceWorkerPluginOptions {
  /**
   * Cache-name prefix, typically the app's name (e.g. `"dicom-viewer"`). The final
   * cache key is `` `${cacheName}-${buildId}` ``.
   */
  cacheName: string
  /**
   * Paths to precache on install. Default: manifest + favicon + PWA icons.
   */
  precache?: string[]
  /** Output filename (default `"sw.js"`). */
  fileName?: string
}

const DEFAULT_PRECACHE = [
  "/manifest.json",
  "/favicon.ico",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
]

/**
 * Vite plugin that emits a stamped `dist/sw.js` from {@link SERVICE_WORKER_SOURCE}.
 *
 * The build id is a short content hash of the emitted (hashed) asset filenames, so
 * it changes whenever the app's output changes — which is what makes the browser
 * detect a new worker after a deploy. Client build only (skips SSR passes).
 */
export function serviceWorkerPlugin(options: ServiceWorkerPluginOptions): Plugin {
  const { cacheName, precache = DEFAULT_PRECACHE, fileName = "sw.js" } = options
  let isSsr = false
  let outDir = "dist"

  return {
    name: "maxhealth-service-worker",
    apply: "build",
    configResolved(config) {
      // Resolved `ssr` is `false` for a client build, or a string/true for an SSR pass.
      isSsr = config.build.ssr !== false
      outDir = config.build.outDir
    },
    async writeBundle(_outputOptions, bundle) {
      if (isSsr) return

      const hash = createHash("sha256")
      for (const name of Object.keys(bundle).sort()) hash.update(name)
      const buildId = hash.digest("hex").slice(0, 12)

      const source = stampServiceWorker(
        SERVICE_WORKER_SOURCE.split(APP_NAME_PLACEHOLDER).join(cacheName).split(
          PRECACHE_PLACEHOLDER,
        ).join(JSON.stringify(precache)),
        buildId,
      )

      await writeFile(join(outDir, fileName), source, "utf8")
    },
  }
}
