/**
 * Canonical MaxHealth service worker — single source for every PWA (dicom-viewer,
 * consent-app, dtr-app, patient-portal, AIHR, ...). Previously each app shipped its
 * own byte-drifting copy of `public/sw.js` plus a local stamping plugin; this module
 * replaces all of them.
 *
 * Pairs with the page-side `useServiceWorkerUpdate` hook + `ServiceWorkerUpdatePrompt`
 * (the "wait + prompt-to-reload" pattern).
 *
 * Shipped as plain JS (with a `.d.ts` sidecar) because shared-ui is consumed as source
 * and a Vite config externalizes its imports to Node, which cannot type-strip a `.ts`
 * under `node_modules`.
 *
 * Usage in an app's `vite.config.ts`:
 * ```ts
 * import { serviceWorkerPlugin } from "@max-health-inc/shared-ui/vite"
 * export default defineConfig({
 *   plugins: [react(), tailwindcss(), serviceWorkerPlugin({ cacheName: "dicom-viewer" })],
 * })
 * ```
 * The app must NOT keep a `public/sw.js` — the plugin emits `dist/sw.js`.
 */
import { createHash } from "node:crypto"
import { writeFile } from "node:fs/promises"
import { join } from "node:path"

/** Token replaced at build time with the app's cache-name prefix. */
const APP_NAME_PLACEHOLDER = "__APP_NAME__"
/** Token replaced at build time with a unique, content-derived build id. */
export const BUILD_ID_PLACEHOLDER = "__BUILD_ID__"
/** Token replaced at build time with the JSON precache array. */
const PRECACHE_PLACEHOLDER = "__PRECACHE__"

/**
 * The service-worker source, with placeholders the plugin fills in. Stored as a
 * string (not a real module) because it runs in the SW global scope and is written
 * verbatim to `dist/sw.js`.
 *
 * Network strategy: cache-first for hashed static assets, network-first for
 * navigations and everything else, `/api/` bypassed.
 *
 * The cache-first branch guards against cache poisoning on BOTH sides. During a deploy
 * swap a momentarily missing hashed file can resolve to the SPA fallback (index.html,
 * 200); storing that under an asset URL breaks MIME ("Expected a JavaScript-or-Wasm
 * module script ... responded with text/html") on every later load. So it never
 * *stores* an HTML response for an asset, and it never *serves* one either: because
 * cache-first does not revalidate, a client poisoned by an older build would otherwise
 * replay the bad entry forever, surviving reloads. Reading validates the cached entry
 * and evicts it across all cache generations, so a broken client heals itself.
 */
export const SERVICE_WORKER_SOURCE = `// GENERATED by @max-health-inc/shared-ui — do not edit by hand.
// MaxHealth PWA service worker. Network-first with offline fallback.
//
// \`${BUILD_ID_PLACEHOLDER}\` is stamped with a unique per-build id so the browser
// detects a fresh SW after each deploy (firing the in-app update prompt) and the
// \`activate\` handler can purge the previous build's caches.
const CACHE_NAME = "${APP_NAME_PLACEHOLDER}-${BUILD_ID_PLACEHOLDER}";

const PRECACHE_ASSETS = ${PRECACHE_PLACEHOLDER};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_ASSETS))
  );
  // Deliberately NOT calling skipWaiting(): an updated SW must WAIT until the user
  // accepts the in-app prompt (which posts SKIP_WAITING). On first install there is
  // no controller, so it activates anyway.
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.pathname.startsWith("/api/")) return;

  if (url.pathname.match(/\\.(png|jpg|jpeg|webp|svg|gif|ico|woff2?|css|js|wasm|dcm)$/)) {
    event.respondWith(cacheFirst(request));
    return;
  }

  event.respondWith(networkFirst(request));
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

// A cached HTML document served for a .css/.js asset request is the SPA fallback
// (index.html, 200) returned for a momentarily-missing hashed file during a deploy.
// Storing it under the asset URL poisons the cache, so never cache it.
function isHtmlFallback(response) {
  return (response.headers.get("content-type") || "").includes("text/html");
}

// Drop an entry from EVERY cache generation, not just the current CACHE_NAME: a
// poisoned entry was written by an older build, and \`caches.match\` reads across all
// of them, so deleting only the current one would keep serving the poison.
async function evictEverywhere(request) {
  for (const key of await caches.keys()) {
    const cache = await caches.open(key);
    await cache.delete(request);
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  // Validate on READ, not only on write. The write guard below stops NEW poisoning,
  // but any cache poisoned by a build that predates it would otherwise replay HTML
  // for this asset forever — the browser reports that as "Expected a
  // JavaScript-or-Wasm module script but the server responded with text/html", and
  // it survives reloads because cache-first never revalidates. Evict and refetch so
  // an already-broken client heals itself.
  if (cached && isHtmlFallback(cached)) {
    await evictEverywhere(request);
  } else if (cached) {
    return cached;
  }
  try {
    const response = await fetch(request);
    if (response.ok && !isHtmlFallback(response)) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    return new Response("", { status: 408 });
  }
}

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await caches.match(request);
    return cached || new Response("", { status: 408 });
  }
}
`

/**
 * Replace every {@link BUILD_ID_PLACEHOLDER} occurrence with `buildId`, inserted
 * literally (never interpreted as a `String.replace` pattern, so ids with `$` are
 * safe). Returns `source` unchanged when the token is absent.
 * @param {string} source
 * @param {string} buildId
 * @returns {string}
 */
export function stampServiceWorker(source, buildId) {
  if (!source.includes(BUILD_ID_PLACEHOLDER)) return source
  return source.split(BUILD_ID_PLACEHOLDER).join(buildId)
}

/** @type {string[]} */
const DEFAULT_PRECACHE = [
  "/manifest.json",
  "/favicon.ico",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
]

/**
 * Vite plugin that emits a stamped `dist/sw.js` from {@link SERVICE_WORKER_SOURCE}.
 *
 * The build id is a short content hash of the emitted (hashed) asset filenames, so
 * it changes whenever the app's output changes — which is what makes the browser
 * detect a new worker after a deploy. Client build only (skips SSR passes).
 *
 * @param {import("./service-worker").ServiceWorkerPluginOptions} options
 * @returns {import("vite").Plugin}
 */
export function serviceWorkerPlugin(options) {
  const { cacheName, precache = DEFAULT_PRECACHE, fileName = "sw.js" } = options
  let isSsr = false
  let outDir = "dist"

  return {
    name: "maxhealth-service-worker",
    apply: "build",
    configResolved(config) {
      // Resolved `ssr` is `false` for a client build, or a string/true for an SSR pass.
      isSsr = config.build.ssr !== false
      outDir = config.build.outDir
    },
    async writeBundle(_outputOptions, bundle) {
      if (isSsr) return

      const hash = createHash("sha256")
      for (const name of Object.keys(bundle).sort()) hash.update(name)
      const buildId = hash.digest("hex").slice(0, 12)

      const source = stampServiceWorker(
        SERVICE_WORKER_SOURCE.split(APP_NAME_PLACEHOLDER)
          .join(cacheName)
          .split(PRECACHE_PLACEHOLDER)
          .join(JSON.stringify(precache)),
        buildId,
      )

      await writeFile(join(outDir, fileName), source, "utf8")
    },
  }
}
